sed -i "sXstartpage{.*}Xstartpage{15}X" B1-1/paper.tex
sed -i "sXstartpage{.*}Xstartpage{25}X" B1-2/paper.tex
sed -i "sXstartpage{.*}Xstartpage{35}X" B2-1/paper.tex
sed -i "sXstartpage{.*}Xstartpage{47}X" B3-1/paper.tex
sed -i "sXstartpage{.*}Xstartpage{55}X" B3-2/paper.tex
sed -i "sXstartpage{.*}Xstartpage{65}X" B4-1/paper.tex
sed -i "sXstartpage{.*}Xstartpage{79}X" B5-1/paper.tex
sed -i "sXstartpage{.*}Xstartpage{89}X" B5-3/paper.tex
sed -i "sXstartpage{.*}Xstartpage{99}X" B5-4/paper.tex
sed -i "sXstartpage{.*}Xstartpage{111}X" B5-5/paper.tex
sed -i "sXstartpage{.*}Xstartpage{123}X" B6-1/paper.tex
